CREATE DATABASE WOODCHUCK_WARMUP_DB;

CREATE SCHEMA internal_stages;


CREATE STAGE LEGOS;

LIST @WOODCHUCK_WARMUP_DB.internal_stages.LEGOS;

SELECT $1, $2, $3, $4
FROM @WOODCHUCK_WARMUP_DB.internal_stages.legos/colors.csv;

CREATE SCHEMA init_data;

CREATE TEMPORARY TABLE WOODCHUCK_WARMUP_DB.INIT_DATA.lego_colors AS 
SELECT $1 as id,$2 as name,$3 as rgb,$4 as is_trans
FROM @WOODCHUCK_WARMUP_DB.internal_stages.legos/colors.csv
WHERE 1 = 2;

COPY INTO WOODCHUCK_WARMUP_DB.INIT_DATA.LEGO_COLORS
FROM (SELECT TRY_TO_NUMBER($1),$2,$3,$4 FROM @WOODCHUCK_WARMUP_DB.internal_stages.legos/colors.csv)
FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1)

SELECT * FROM WOODCHUCK_WARMUP_DB.INIT_DATA.LEGO_COLORS;

CREATE TABLE WOODCHUCK_WARMUP_DB.INIT_DATA.LEGO_COLORS_IS_TRANS AS 
SELECT c.ID , c.NAME, c.RGB
FROM WOODCHUCK_WARMUP_DB.INIT_DATA.LEGO_COLORS as c
WHERE c.IS_TRANS like 't'

SELECT * FROM LEGO_COLORS_IS_TRANS;

SELECT $1,$2,$3,$4,$5
FROM @WOODCHUCK_WARMUP_DB.internal_stages.legos/themes.csv

CREATE OR REPLACE TABLE WOODCHUCK_WARMUP_DB.INIT_DATA.td_top_themes_this_month AS
SELECT 'Star Wars' as Theme,COUNT($2) as Count
FROM @WOODCHUCK_WARMUP_DB.internal_stages.legos/themes.csv
WHERE $2 like '%Star Wars%'

SELECT * FROM WOODCHUCK_WARMUP_DB.INIT_DATA.td_top_themes_this_month;
